language: elixir
elixir:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.3
  - 23.0
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 21.3
    - elixir: 1.6
      otp_release: 22.3
    - elixir: 1.6
      otp_release: 23.0
    - elixir: 1.7
      otp_release: 23.0
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 23.0
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 23.0
    - elixir: 1.10
      otp_release: 19.3
    - elixir: 1.10
      otp_release: 20.3
cache:
  directories:
    - _build
    - deps
install: mix local.rebar --force; mix local.hex --force; mix deps.get
script: export MIX_ENV=test; mix test --cover; mix credo --strict
